name:                thrift-cli
version:             0.1.0.0
github:              "mut0u/thrift-cli"
license:             BSD3
author:              "savior"
maintainer:          "michael.savior@gmail.com"
copyright:           "2019 savior"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mut0u/thrift-cli#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  thrift-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thrift-cli

tests:
  thrift-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thrift-cli
