/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2019-11-15")
public class Inner implements org.apache.thrift.TBase<Inner, Inner._Fields>, java.io.Serializable, Cloneable, Comparable<Inner> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Inner");

  private static final org.apache.thrift.protocol.TField INNER_STR_FIELD_DESC = new org.apache.thrift.protocol.TField("inner_str", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INNER_DOUBLE_FIELD_DESC = new org.apache.thrift.protocol.TField("inner_double", org.apache.thrift.protocol.TType.DOUBLE, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new InnerStandardSchemeFactory());
    schemes.put(TupleScheme.class, new InnerTupleSchemeFactory());
  }

  public String inner_str; // required
  public double inner_double; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INNER_STR((short)1, "inner_str"),
    INNER_DOUBLE((short)7, "inner_double");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INNER_STR
          return INNER_STR;
        case 7: // INNER_DOUBLE
          return INNER_DOUBLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INNER_DOUBLE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INNER_STR, new org.apache.thrift.meta_data.FieldMetaData("inner_str", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INNER_DOUBLE, new org.apache.thrift.meta_data.FieldMetaData("inner_double", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Inner.class, metaDataMap);
  }

  public Inner() {
  }

  public Inner(
    String inner_str,
    double inner_double)
  {
    this();
    this.inner_str = inner_str;
    this.inner_double = inner_double;
    setInner_doubleIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Inner(Inner other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetInner_str()) {
      this.inner_str = other.inner_str;
    }
    this.inner_double = other.inner_double;
  }

  public Inner deepCopy() {
    return new Inner(this);
  }

  @Override
  public void clear() {
    this.inner_str = null;
    setInner_doubleIsSet(false);
    this.inner_double = 0.0;
  }

  public String getInner_str() {
    return this.inner_str;
  }

  public Inner setInner_str(String inner_str) {
    this.inner_str = inner_str;
    return this;
  }

  public void unsetInner_str() {
    this.inner_str = null;
  }

  /** Returns true if field inner_str is set (has been assigned a value) and false otherwise */
  public boolean isSetInner_str() {
    return this.inner_str != null;
  }

  public void setInner_strIsSet(boolean value) {
    if (!value) {
      this.inner_str = null;
    }
  }

  public double getInner_double() {
    return this.inner_double;
  }

  public Inner setInner_double(double inner_double) {
    this.inner_double = inner_double;
    setInner_doubleIsSet(true);
    return this;
  }

  public void unsetInner_double() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __INNER_DOUBLE_ISSET_ID);
  }

  /** Returns true if field inner_double is set (has been assigned a value) and false otherwise */
  public boolean isSetInner_double() {
    return EncodingUtils.testBit(__isset_bitfield, __INNER_DOUBLE_ISSET_ID);
  }

  public void setInner_doubleIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __INNER_DOUBLE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INNER_STR:
      if (value == null) {
        unsetInner_str();
      } else {
        setInner_str((String)value);
      }
      break;

    case INNER_DOUBLE:
      if (value == null) {
        unsetInner_double();
      } else {
        setInner_double((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INNER_STR:
      return getInner_str();

    case INNER_DOUBLE:
      return Double.valueOf(getInner_double());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INNER_STR:
      return isSetInner_str();
    case INNER_DOUBLE:
      return isSetInner_double();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Inner)
      return this.equals((Inner)that);
    return false;
  }

  public boolean equals(Inner that) {
    if (that == null)
      return false;

    boolean this_present_inner_str = true && this.isSetInner_str();
    boolean that_present_inner_str = true && that.isSetInner_str();
    if (this_present_inner_str || that_present_inner_str) {
      if (!(this_present_inner_str && that_present_inner_str))
        return false;
      if (!this.inner_str.equals(that.inner_str))
        return false;
    }

    boolean this_present_inner_double = true;
    boolean that_present_inner_double = true;
    if (this_present_inner_double || that_present_inner_double) {
      if (!(this_present_inner_double && that_present_inner_double))
        return false;
      if (this.inner_double != that.inner_double)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_inner_str = true && (isSetInner_str());
    list.add(present_inner_str);
    if (present_inner_str)
      list.add(inner_str);

    boolean present_inner_double = true;
    list.add(present_inner_double);
    if (present_inner_double)
      list.add(inner_double);

    return list.hashCode();
  }

  @Override
  public int compareTo(Inner other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetInner_str()).compareTo(other.isSetInner_str());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInner_str()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inner_str, other.inner_str);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInner_double()).compareTo(other.isSetInner_double());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInner_double()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inner_double, other.inner_double);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Inner(");
    boolean first = true;

    sb.append("inner_str:");
    if (this.inner_str == null) {
      sb.append("null");
    } else {
      sb.append(this.inner_str);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("inner_double:");
    sb.append(this.inner_double);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InnerStandardSchemeFactory implements SchemeFactory {
    public InnerStandardScheme getScheme() {
      return new InnerStandardScheme();
    }
  }

  private static class InnerStandardScheme extends StandardScheme<Inner> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Inner struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INNER_STR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.inner_str = iprot.readString();
              struct.setInner_strIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // INNER_DOUBLE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.inner_double = iprot.readDouble();
              struct.setInner_doubleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Inner struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.inner_str != null) {
        oprot.writeFieldBegin(INNER_STR_FIELD_DESC);
        oprot.writeString(struct.inner_str);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(INNER_DOUBLE_FIELD_DESC);
      oprot.writeDouble(struct.inner_double);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InnerTupleSchemeFactory implements SchemeFactory {
    public InnerTupleScheme getScheme() {
      return new InnerTupleScheme();
    }
  }

  private static class InnerTupleScheme extends TupleScheme<Inner> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Inner struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetInner_str()) {
        optionals.set(0);
      }
      if (struct.isSetInner_double()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetInner_str()) {
        oprot.writeString(struct.inner_str);
      }
      if (struct.isSetInner_double()) {
        oprot.writeDouble(struct.inner_double);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Inner struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.inner_str = iprot.readString();
        struct.setInner_strIsSet(true);
      }
      if (incoming.get(1)) {
        struct.inner_double = iprot.readDouble();
        struct.setInner_doubleIsSet(true);
      }
    }
  }

}

