/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2019-11-15")
public class Test2Message implements org.apache.thrift.TBase<Test2Message, Test2Message._Fields>, java.io.Serializable, Cloneable, Comparable<Test2Message> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Test2Message");

  private static final org.apache.thrift.protocol.TField MS_FIELD_DESC = new org.apache.thrift.protocol.TField("ms", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new Test2MessageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new Test2MessageTupleSchemeFactory());
  }

  public List<DemoMessage> ms; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MS((short)1, "ms");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MS
          return MS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MS, new org.apache.thrift.meta_data.FieldMetaData("ms", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "DemoMessage"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Test2Message.class, metaDataMap);
  }

  public Test2Message() {
  }

  public Test2Message(
    List<DemoMessage> ms)
  {
    this();
    this.ms = ms;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Test2Message(Test2Message other) {
    if (other.isSetMs()) {
      List<DemoMessage> __this__ms = new ArrayList<DemoMessage>(other.ms.size());
      for (DemoMessage other_element : other.ms) {
        __this__ms.add(other_element);
      }
      this.ms = __this__ms;
    }
  }

  public Test2Message deepCopy() {
    return new Test2Message(this);
  }

  @Override
  public void clear() {
    this.ms = null;
  }

  public int getMsSize() {
    return (this.ms == null) ? 0 : this.ms.size();
  }

  public java.util.Iterator<DemoMessage> getMsIterator() {
    return (this.ms == null) ? null : this.ms.iterator();
  }

  public void addToMs(DemoMessage elem) {
    if (this.ms == null) {
      this.ms = new ArrayList<DemoMessage>();
    }
    this.ms.add(elem);
  }

  public List<DemoMessage> getMs() {
    return this.ms;
  }

  public Test2Message setMs(List<DemoMessage> ms) {
    this.ms = ms;
    return this;
  }

  public void unsetMs() {
    this.ms = null;
  }

  /** Returns true if field ms is set (has been assigned a value) and false otherwise */
  public boolean isSetMs() {
    return this.ms != null;
  }

  public void setMsIsSet(boolean value) {
    if (!value) {
      this.ms = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MS:
      if (value == null) {
        unsetMs();
      } else {
        setMs((List<DemoMessage>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MS:
      return getMs();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MS:
      return isSetMs();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Test2Message)
      return this.equals((Test2Message)that);
    return false;
  }

  public boolean equals(Test2Message that) {
    if (that == null)
      return false;

    boolean this_present_ms = true && this.isSetMs();
    boolean that_present_ms = true && that.isSetMs();
    if (this_present_ms || that_present_ms) {
      if (!(this_present_ms && that_present_ms))
        return false;
      if (!this.ms.equals(that.ms))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_ms = true && (isSetMs());
    list.add(present_ms);
    if (present_ms)
      list.add(ms);

    return list.hashCode();
  }

  @Override
  public int compareTo(Test2Message other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMs()).compareTo(other.isSetMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ms, other.ms);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Test2Message(");
    boolean first = true;

    sb.append("ms:");
    if (this.ms == null) {
      sb.append("null");
    } else {
      sb.append(this.ms);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class Test2MessageStandardSchemeFactory implements SchemeFactory {
    public Test2MessageStandardScheme getScheme() {
      return new Test2MessageStandardScheme();
    }
  }

  private static class Test2MessageStandardScheme extends StandardScheme<Test2Message> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Test2Message struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
                struct.ms = new ArrayList<DemoMessage>(_list20.size);
                DemoMessage _elem21;
                for (int _i22 = 0; _i22 < _list20.size; ++_i22)
                {
                  _elem21 = new DemoMessage();
                  _elem21.read(iprot);
                  struct.ms.add(_elem21);
                }
                iprot.readListEnd();
              }
              struct.setMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Test2Message struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ms != null) {
        oprot.writeFieldBegin(MS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ms.size()));
          for (DemoMessage _iter23 : struct.ms)
          {
            _iter23.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class Test2MessageTupleSchemeFactory implements SchemeFactory {
    public Test2MessageTupleScheme getScheme() {
      return new Test2MessageTupleScheme();
    }
  }

  private static class Test2MessageTupleScheme extends TupleScheme<Test2Message> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Test2Message struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMs()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMs()) {
        {
          oprot.writeI32(struct.ms.size());
          for (DemoMessage _iter24 : struct.ms)
          {
            _iter24.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Test2Message struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list25 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.ms = new ArrayList<DemoMessage>(_list25.size);
          DemoMessage _elem26;
          for (int _i27 = 0; _i27 < _list25.size; ++_i27)
          {
            _elem26 = new DemoMessage();
            _elem26.read(iprot);
            struct.ms.add(_elem26);
          }
        }
        struct.setMsIsSet(true);
      }
    }
  }

}

